### ISSUE TITLE
手势操作,滑动返回。

### ISSUE THREAD

**Issue by fjcgreat** [lanceli/cnodejs-ionic#1]
我使用6plus，当我点进贴子的详细，如果要返回列表页的话，想要按到返回按钮很困难，我又不想总是去使用home键，加个swipe事件吧.

本来我是想自己去添加 ， 按照你的doc，用浏览器调试时，跨域你是怎么解决的？

**Comment by lanceli** [comment]
恩恩 之前也有这个功能计划
p.s. ionic的roadmap里有swipe to back功能 说beta14是final beta 不过也不知道啥时候能出1.0正式版

你是本地搭建的nodeclub？
跨域两种方案：
- 关闭chrome的web security

```
open -a  /Applications/Google\ Chrome.app  --args --disable-web-security --allow-file-access-from-files
```
- nginx支持跨域请求，cnode生产环境已启用

```
add_header Access-Control-Allow-Origin *;
```

http://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx/

**Comment by ckken** [comment]
哈哈 我也在等这个功能 不过是时候期待 react native了

**Comment by lanceli** [comment]
@ckken nightly已经有了 但 https://github.com/driftyco/ionic/issues/2376 问题还在 我这暂时不能升级
react native确实值得期待

**Comment by lanceli** [comment]
app store 2.0.0今日已上架 :v: 
e027deef169407e400dedb66877027dbef52c825

**Comment by zhyzhy782** [comment]
Hey! 
I know it might be something strange, but  still so  interesting, you have to see it here http://fund.auctionhook.com/e7gpu/0

Bests, zhyzhy782

**Comment by zhyzhy782** [comment]
Yo! 

I thought you  might be interested  it that new  and very nice stuff, just take a look  here http://have.flexitarianfamily.com/e7fc/1

Best Wishes, zhyzhy782
