### ISSUE TITLE
运行grunt serve报错

### ISSUE THREAD

**Issue by microlv** [lanceli/cnodejs-ionic#11]
这是什么情况？
![qq 20150306174745](https://cloud.githubusercontent.com/assets/5182589/6523235/efae2dde-c428-11e4-8204-048920781f26.png)
![image](https://cloud.githubusercontent.com/assets/5182589/6523262/13db49e4-c429-11e4-9114-29ce72ea9219.png)

**Comment by lanceli** [comment]
compass 木有装

**Comment by microlv** [comment]
@lanceli 
compass/ionic/cordova都装了。这错误是？
![image](https://cloud.githubusercontent.com/assets/5182589/6555583/2a1c56b4-c6a2-11e4-9896-3472e28a11c5.png)

**Comment by lanceli** [comment]
https://cnodejs.org/topic/54b4db04edf686411e1b9d7f#54b51ac3edf686411e1b9dcf

https://github.com/diegonetto/generator-ionic/issues/15#issuecomment-38075095

generator-ionic window下的一个bug

**Comment by microlv** [comment]
总算是跑起来了，关于这些遇到的问题是否可以写个Question放在Readme里？
如果有需要，我这次的经历可以写上去~

**Comment by lanceli** [comment]
可以啊 你能写就那再好不过了 给我个 pr 或者 贴这里

**Comment by microlv** [comment]
OK，提PR吧，让领导审核。
还有就是，我看app里的angular代码，不支持压缩吧？还是说你不打算做压缩？

**Comment by lanceli** [comment]
:+1: 
支持压缩的 grunt compress

https://github.com/diegonetto/generator-ionic#grunt-compress
