### ISSUE TITLE
增加如何登录的提示信息

### ISSUE THREAD

**Issue by lanceli** [lanceli/cnodejs-ionic#2]
首次点击登录时 
- 提示用户如何扫码
- 提示用户可以复制token，长按并登录

非首次登录不再提示

**Comment by alsotang** [comment]
只要扫码就好了吧，毕竟现在的 iphone 和 安卓 都是有摄像头的

**Comment by lanceli** [comment]
确实对普通用户扫码足够了，长按登录功能是因为开发测试时登录登出较频繁，并且有时不方便扫码（比如在路上）。
修改如下：
- 提示信息只提示用户如何扫码，并且始终提示。
- 长按功能保留但不提示用户。
