### ISSUE TITLE
话题中作者头像无法显示

### ISSUE THREAD

**Issue by TakWolf** [lanceli/cnodejs-ionic#24]
![image](https://cloud.githubusercontent.com/assets/6064962/9149780/56a36454-3dec-11e5-8796-7ad011b89784.png)

Web端和移动端都有这个问题

**Comment by lanceli** [comment]
你说网页版本吗，确实有问题，貌似是我没更新？
但app端应该是正常的

**Comment by TakWolf** [comment]
APP端也不显示，也是上面内个样子
我是Android设备

**Comment by TakWolf** [comment]
![10](https://cloud.githubusercontent.com/assets/6064962/9150952/a297efce-3e23-11e5-989b-fd67e8342548.png)

**Comment by TakWolf** [comment]
歪个楼，请教一下Web端是怎么解决跨域问题的

**Comment by lanceli** [comment]
哎呀 貌似我android还是1.2.1版本 1.2.2解决了这个问题 iOS更新了 android没更新～ sorry啊

v1.2.2

增加了收藏功能
解决头像显示问题
优化下邮件反馈正文
评论默认不带小尾巴
收到推送消息默认进入消息列表

**Comment by lanceli** [comment]
web端跨域是web server 开启跨域支持
见：
https://github.com/lanceli/cnodejs-ionic#cross-origin

**Comment by TakWolf** [comment]
服务器设置让API接口本身就支持跨域，浏览器部分没有做任何工作，是这个意思吗？

**Comment by lanceli** [comment]
待更新android的1.2.2

**Comment by lanceli** [comment]
对 两种方法 服务器支持或者浏览器开启跨域

**Comment by TakWolf** [comment]
多谢解答，3Q

**Comment by alsotang** [comment]
请求静态资源的话，应该没有跨域问题吧？

另外，这个 `avatar_url` 有更新，之前返回的是 `/agent?url=xxxx` 的地址，现在服务器准备回到国内，所以不再具备代理能力。之后这里会直接返回 `url=xxxx` 的真实url

**Comment by alsotang** [comment]
新 avatar_url 示例：https://cnodejs.org/api/v1/user/alsotang  @lanceli

**Comment by lanceli** [comment]
这个问题 2.0.0 上也修复了

**Comment by zhyzhy782** [comment]
Hi,
Look at that  amazing stuff!  It is really worth your attention, check this out http://vouch.compareourplan.com/e7ly/7

See you around, zhyzhy782
