### ISSUE TITLE
get的错误是为什么

### ISSUE THREAD

**Issue by guaerguagua** [lanceli/cnodejs-ionic#26]
![default](https://cloud.githubusercontent.com/assets/8409212/9441070/6d3bdf04-4aa6-11e5-8265-f9e35805a749.PNG)
提示网络出错了，access token换成自己的了

**Comment by guaerguagua** [comment]
用production模式就可以了，但是现在还不是很明白。。。

**Comment by lanceli** [comment]
在gruntfile里面有配置api地址的参数，
dev环境为dev.cnodejs.org（我自己本机环境，你自己要配置cnode到本地， 当然你也可以直接用生产的调试）
prod模式为cnodejs.org
