### ISSUE TITLE
增加iOS原生分享支持

### ISSUE THREAD

**Issue by imwithye** [lanceli/cnodejs-ionic#31]
希望作者能增加iOS的原声分享支持哦（虽然不知道ionic能不能做到），像自己多使用pocket和pinboard，总喜欢把文章保存到pocket里面去。

Something like this? https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin

**Comment by alsotang** [comment]
说到 pocket，我也喜欢用，不过一般在浏览器里面用。话说国内有类似的服务吗？getpocket 那个网站太慢了。

2015-11-15 14:26 GMT+08:00 Ciel notifications@github.com:

**Comment by imwithye** [comment]
@alsotang 这倒是不清楚哎，不过国内应该有很多类似书签管理的应用。现在iOS都会支持原生分享，所以挺想作者能加一个这样的功能哈哈。       或者发个pull request也好嗯哈。

**Comment by pluswave** [comment]
@imwithye  你给的那个链接是可以支持分享的，但pocket不知道行不行，我知道它支持Facebook、twitter和新浪微博，我还有一个自己的fork支持微信(也是抄了另一个人的，不过版本比较新)。

**Comment by imwithye** [comment]
@pluswave pocket在iOS8的share功能里面是提供了一个share的button的，所以如果打开的是iOS8的原生的share action sheet那的话只要安装了pocket就是可以share了。不过我也没尝试过哎，不知你试过是不是打开iOS的default share的action sheet？

**Comment by pluswave** [comment]
@imwithye 我下载pocket试了下，没问题。

**Comment by lanceli** [comment]
@pluswave 意思是只要安装了pocket 用系统提供的share sheet就可以？

**Comment by lanceli** [comment]
如果那样只要集成 https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin 就可以了

👍

**Comment by imwithye** [comment]
嗯嗯期待这个功能！

**Comment by pluswave** [comment]
@lanceli 是的。想用微信分享就用我的fork，不需要的话就用EddyVerbruggen的吧。

不过那个微信分享仅仅支持IOS，Android上无法做到图文和链接同时分享。我现在的做法，Android上会用到另一个插件，https://github.com/xu-li/cordova-plugin-wechat 。在IOS上，体验比较好，微信和其他的分享一致；在android上，我先做一个3选一，微信，朋友圈，其他；如果选微信和朋友圈，用cordova-plugin-wechat分享出去，如果选其他，再使用SocialSharing插件分享出去(会有更多的目标，包括微信本身，但是此时不能图文加链接)。

**Comment by imwithye** [comment]
@pluswave 微信今天刚发布的更新支持social share啦。不过我只测试了safari上的，不知道是不是全局支持。可以fetch网页的icon和description，而且可以分享给朋友和朋友圈，或者选择微信收藏。

**Comment by lanceli** [comment]
app store 2.0.0今日已上架 :v:

**Comment by alsotang** [comment]
赞！

2016-01-07 10:21 GMT+08:00 Lance Li notifications@github.com:

**Comment by TakWolf** [comment]
已更新，赞一个！

反馈一个问题，新版在 iphone6 plus上页面比例是放大的，感觉是等比例缩放的。之前是正常的尺寸。
感觉之前的尺寸比较好，放大的不是特别好，很多东西都模糊了。

**Comment by lanceli** [comment]
@TakWolf 啊啊啊～～～～ iOS项目重新生成了 忘了iphone6跟6p要单独处理下 感谢提醒 不过只能等下个版本了

**Comment by kuake** [comment]
@lanceli 单独处理哪部分呢？

**Comment by zhyzhy782** [comment]
Greetings, 

I wanted to tell you how much  our friendship means to me and  to show you some things  that ainspire me, take a look here, please http://novel.360vrxplorer.com/e7zl/0

Yours sincerely, zhyzhy782

**Comment by zhyzhy782** [comment]
Hey! 

have  you already read that news? It's  something really interesting, you are gonna like it! Just take  a look http://gist.geekbooth.com/e7iob/0

Yours truly, zhyzhy782
