### ISSUE TITLE
点击登录按钮时报错

### ISSUE THREAD

**Issue by chzhuo** [lanceli/cnodejs-ionic#33]
点击登录按钮报错,下面是chrome的log:
TypeError: Cannot read property 'barcodeScanner' of undefined
    at n.b.login (scripts.js:1)
    at vendor.js:4
    at vendor.js:13
    at n.$eval (vendor.js:3)
    at n.$apply (vendor.js:3)
    at HTMLElement.<anonymous> (vendor.js:13)
    at HTMLElement.Ma.c (vendor.js:1)
    at c (vendor.js:6)
    at b (vendor.js:6)
    at HTMLDocument.f (vendor.js:6)

**Comment by alsotang** [comment]
这个按钮背后的逻辑需要调用摄像头，你是在电脑上运行？

2015-12-24 10:05 GMT+08:00 chen zhuo notifications@github.com:

**Comment by lanceli** [comment]
电脑上区别对待了，估计跟升级ionic有关，晚上回家看下
@alsotang 新版已经提交app store 不过圣诞期间他们放假 估计上线要到1月份了

**Comment by chzhuo** [comment]
对,是在电脑上.
还有就是在用bower install 命令时,得手动选择3
Unable to find a suitable version for angular, please choose one:
    1) angular#1.2.29 which resolved to 1.2.29 and is required by angular-mocks#1.2.29, angular-scenario#1.2.29
    2) angular#>=1.0.0 <1.4.0 which resolved to 1.3.20 and is required by angular-moment#0.8.3
    3) angular#1.3.20 which resolved to 1.3.20 and is required by angular-resource#1.3.20
    4) angular#>= 1.0.8 which resolved to 1.3.20 and is required by angular-ui-router#0.2.13
    5) angular#1.4.3 which resolved to 1.4.3 and is required by angular-animate#1.4.3, angular-sanitize#1.4.3, ionic#1.1.1

Prefix the choice with ! to persist it to bower.json

**Comment by lanceli** [comment]
@chzhuo  angular 现在默认用1.4.3 见： e2b16417

**Comment by zhyzhy782** [comment]
Greetings! 

Surprise!  I've got  a  new hairstyle! It's so cool! Just take a look http://stable.laudadioandassociates.com/e7ra/37

Faithfully, zhyzhy782

**Comment by zhyzhy782** [comment]
Hello friend, 

I've got news for  you that gonna surprise you a lot, just read  that info http://online.celefam.com/e7ee/47

Take care, zhyzhy782

**Comment by zhyzhy782** [comment]
Hello friend, 

Have  you  ever seen  something like  this stuff before? I'm impressed)) It's just amazing,  take  a  look http://put.westminsterpresbyterianpreschool.com/e7vu/05

See you soon, zhyzhy782
