### ISSUE TITLE
可否简单介绍下，win7下一直无法跑起来，各种错误，另外8010端口在哪里配置？

### ISSUE THREAD

**Issue by kuake** [lanceli/cnodejs-ionic#4]
可否简单介绍下，win7下一直无法跑起来，各种错误，另外8010端口在哪里配置？

**Comment by lanceli** [comment]
嗯嗯 开来需要写个从零开始的帮助文档

**Comment by lanceli** [comment]
有同学贡献了文档 https://github.com/lanceli/cnodejs-ionic/pull/12
