### ISSUE TITLE
推送貌似不好使了

### ISSUE THREAD

**Issue by TakWolf** [lanceli/cnodejs-ionic#41]
设备是iphone6sp

之前是好使的，今天突然发现收不到推送了

**Comment by TakWolf** [comment]
Android的设备同样也收不到对推送了

**Comment by alsotang** [comment]
推送那块的服务端代码已经被我干掉了。。。不推了吧。。。

2016-04-23 23:23 GMT+08:00 TakWolf notifications@github.com:

**Comment by TakWolf** [comment]
........

**Comment by atjiu** [comment]
………
