### ISSUE TITLE
没任何反应？

### ISSUE THREAD

**Issue by kuake** [lanceli/cnodejs-ionic#5]
C:\cnodejsIonic>grunt serve --force
Running "serve" task

Running "clean:dist" (clean) task
Cleaning .tmp...OK
Cleaning www/css...OK
Cleaning www/fonts...OK
Cleaning www/img...OK
Cleaning www/index.html...OK
Cleaning www/js...OK
Cleaning www/lib...OK
Cleaning www/templates...OK

Running "clean:server" (clean) task

Running "ngconstant:development" (ngconstant) task
Creating module cnodejs.config at app/js/config.js...OK

Running "wiredep:app" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task

Running "copy:styles" (copy) task

Done, without errors.

Running "copy:vendor" (copy) task

Done, without errors.

Running "copy:fonts" (copy) task

Done, without errors.

Running "compass:server" (compass) task
directory .tmp/css
        write .tmp/css/main.css (0.03s)

Done, without errors.

Running "autoprefixer:dist" (autoprefixer) task
Prefixed file ".tmp/css/main.css" created.

Running "newer:copy:app" (newer) task

Running "copy:app" (copy) task
Created 35 directories, copied 250 files

Running "newer-postrun:copy:app:1:C:\java\mygit\cnodejsIonic\node_modules\grunt-newer.cache" (newer-postrun) task

Running "newer:copy:tmp" (newer) task

Running "copy:tmp" (copy) task
Copied 1 files

Running "newer-postrun:copy:tmp:2:C:\java\mygit\cnodejsIonic\node_modules\grunt-newer.cache" (newer-postrun) task

Running "concurrent:ionic" (concurrent) task
Running "watch" taskRunning "ionic:serve" (ionic) task

Waiting...Warning: undefined is not a function Used --force, continuing.

Done, but with warnings.

Execution Time (2015-01-22 10:07:25 UTC)
loading tasks  4ms  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 50%
ionic:serve    4ms  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 50%
Total 8ms

**Comment by lanceli** [comment]
grunt serve -v 的结果贴下
不要用force

**Comment by lanceli** [comment]
只贴报错的部分就可以

**Comment by kuake** [comment]
Running "ionic:serve" (ionic) task
Warning: undefined is not a function Use --force to continue.

```
Watching app for changes.
```

Watching demo for changes.
Warning:  Use --force to continue.Watching hooks for changes.

```
Watching node_modules for changes.
```

Aborted due to warnings.Watching resources for changes.

Watching test for changes.
Watching www for changes.

Execution Time (2015-01-23 02:33:01 UTC)
loading tasks                                                                         47ms  0%
serve                                                                                  0ms  0%
clean:dist                                                                           839ms  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 4%
clean:server                                                                          16ms  0%
ngconstant:development                                                                31ms  0%
wiredep:app                                                                           2.1s  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 11%
wiredep:sass                                                                          32ms  0%
concurrent:server                                                                     6.1s  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 32%
autoprefixer:dist                                                                     31ms  0%
newer:copy:app                                                                       858ms  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 5%
copy:app                                                                              6.6s  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 35%
newer-postrun:copy:app:1:C:\java\mygit\cnodejsIonic\node_modules\grunt-newer.cache    9ms  0%
newer:copy:tmp                                                                        20ms  0%
copy:tmp                                                                              16ms  0%
newer-postrun:copy:tmp:2:C:\java\mygit\cnodejsIonic\node_modules\grunt-newer.cache    0ms  0%
concurrent:ionic                                                                      2.2s  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 12%
Total 18.8s

**Comment by kuake** [comment]
没有明显的error

**Comment by lanceli** [comment]
```
node -v
npm -v
ionic -v
cordova -v
compass -v
```

**Comment by kuake** [comment]
node :v0.10.34
npm:1.4.28
ionic:1.3.2
cordova:4.2.0
compass:Compass 1.0.3 (Polaris)

**Comment by lanceli** [comment]
这个是怎么解决的？

**Comment by kuake** [comment]
var spawn = require('child_process').spawn;
替换为：var spawn = require('win-spawn').spawn;
多了个.spawn。
另外：var exec = require('child_process').exec目前还没替换，是不是也需要修改？

**Comment by Jekin6** [comment]
我弄了好久才把这个开发环境跑起来，呵呵。我现在改动如下，就把var spawn = require('child_process').spawn; 改为var spawn = require('win-spawn'); 另外，你npm安装win-spawn时要除了用-g安装外 最好到项目根目录（不用-g）再安装一下 这时在./node_modules目录下有个win-spawn文件夹。
var _ = require('lodash');
var path = require('path');
var cordovaCli = require('cordova');
var spawn = require('win-spawn');
var exec = require('child_process').exec; //require('child_process').exec;

**Comment by lanceli** [comment]
有同学贡献了windows问题相关文档 https://github.com/lanceli/cnodejs-ionic/pull/12
