### ISSUE TITLE
输入http://localhost:8100/报错

### ISSUE THREAD

**Issue by kuake** [lanceli/cnodejs-ionic#8]
Uncaught Error: [$injector:unpr] Unknown provider: $$qProvider <- $$q <- $animate <- $compile

**Comment by kuake** [comment]
AngularJS v1.2.28

**Comment by lanceli** [comment]
```
git pull
bower update
```

**Comment by kuake** [comment]
Unable to find a suitable version for angular, please choose one:
    1) angular#1.2.28 which resolved to 1.2.28 and is required by angular-mocks#1.2.28, angular-scenario#1.2.28
    2) angular#1.3.6 which resolved to 1.3.6 and is required by angular-animate#1.3.6, angular-sanitize#1.3.6, ionic#1.0.0-beta.14
    3) angular#>=1.0.0 <1.4.0 which resolved to 1.3.10 and is required by angular-moment#0.8.3
    4) angular#1.3.10 which resolved to 1.3.10 and is required by angular-resource#1.3.10
    5) angular#>= 1.0.8 which resolved to 1.3.10 and is required by angular-ui-router#0.2.13Prefix the choice with ! to persist it to bower.json

**Comment by kuake** [comment]
哪个合适？

**Comment by lanceli** [comment]
2: 1.3.6

**Comment by kuake** [comment]
多谢，看到效果了，回头再看看那几个坑

**Comment by lanceli** [comment]
嗯嗯 方便的话都贴到这 感谢
